name: 기능 제안
description: 기능을 제안하고 싶다면 이 템플릿을 통해 남겨주세요.
title: "[제안]: ..."
labels: ["enhancement"]
assignees:
  - nsce9806q
  - krapie
  - cspyo
body:
  - type: input
    id: summary
    attributes:
      label: 한 줄 설명
      description: 제안하고 싶은 기능을 간략하게 한 줄로 설명해주세요.
      placeholder: 제안하고 싶은 기능을 간략하게 한 줄로 설명해주세요.
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: 상세 설명
      description: 기능에 대한 상세 설명을 적어주세요.
      value: "- ** 제안 배경 **\n- ** 기능 제안 **\n- ** 구현 방법 **"
    validations:
      required: true
  - type: textarea
    id: more_details
    attributes:
      label: 추가 사항
      description: 기능과 관련된 추가적인 사항이 있다면 적어주세요.
      value: "- ** 관련 레퍼런스 **\n- ** 관련 스크린샷 **"
    validations:
      required: false